name: rutgers
dependencies:
  - nomkl
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - bokeh
  - matplotlib
  - hvplot
  - panel
  - dask
  - numba
  - jupyter
  - pygithub
  - pip
  - pip:
    - contest